repos:
  # 1) Commitizen
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      # Este hook se ejecuta en el pre-commit
      - id: commitizen

  # 2) Prettier (mirrors-prettier)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: [--write, .]
        # "files" define el patrón de archivos a los que se aplica
        files: \.(js|jsx|ts|tsx|json|css|scss|md)$

  # 3) ESLint (hook local)
  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint
        entry: npx
        args: [eslint, --fix, .]
        language: node
        # "files" define el patrón de archivos que ESLint corregirá
        files: \.(js|jsx|ts|tsx)$
