repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: [--write, .]
        files: \.(js|jsx|ts|tsx|json|css|scss|md)$

  - repo: local
    hooks:
      - id: eslint
        name: Run ESLint
        entry: npx
        args: [eslint, --fix, .]
        language: node
        files: \.(js|jsx|ts|tsx)$
